"""lawyer request removed fields and doc url for messages

Revision ID: 277757d9f678
Revises: 19098da12b13
Create Date: 2025-05-17 21:48:10.643310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '277757d9f678'
down_revision: Union[str, None] = '19098da12b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_requests', 'estimated_response_time')
    op.drop_column('lawyer_requests', 'document_content')
    op.add_column('messages', sa.Column('document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'document_url')
    op.add_column('lawyer_requests', sa.Column('document_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lawyer_requests', sa.Column('estimated_response_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
