"""enum changes for chat_service

Revision ID: 3fd8605a5e7f
Revises: c8f4214cb03b
Create Date: 2025-05-05 00:27:02.444055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd8605a5e7f'
down_revision: Union[str, None] = 'c8f4214cb03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Обновляем ChatTypeEnum, добавляя новые значения
    op.execute("ALTER TYPE chattypeenum ADD VALUE IF NOT EXISTS 'ai'")
    op.execute("ALTER TYPE chattypeenum ADD VALUE IF NOT EXISTS 'lawyer'")

    # Обновляем MessageSenderTypeEnum, добавляя новые значения
    op.execute("ALTER TYPE messagesendertypeenum ADD VALUE IF NOT EXISTS 'user'")
    op.execute("ALTER TYPE messagesendertypeenum ADD VALUE IF NOT EXISTS 'ai'")
    op.execute("ALTER TYPE messagesendertypeenum ADD VALUE IF NOT EXISTS 'lawyer'")

    # Обновляем MessageStatusEnum, добавляя новые значения (sent уже существует)
    op.execute("ALTER TYPE messagestatusenum ADD VALUE IF NOT EXISTS 'error'")
    op.execute("ALTER TYPE messagestatusenum ADD VALUE IF NOT EXISTS 'read'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # В PostgreSQL нельзя удалить значения enum, поэтому тут ничего не делаем
    pass
    # ### end Alembic commands ###