"""add new table refresh_sessions_lawyer

Revision ID: 506ac4444628
Revises: 277757d9f678
Create Date: 2025-05-17 23:00:55.743870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506ac4444628'
down_revision: Union[str, None] = '277757d9f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_sessions_lawyer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('expires_in', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_sessions_lawyer')
    # ### end Alembic commands ###
