"""changed table model fields

Revision ID: 6e0bc9e5e22e
Revises: abbbd77f5297
Create Date: 2025-05-08 15:03:21.935856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0bc9e5e22e'
down_revision: Union[str, None] = 'abbbd77f5297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('example', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'example')
    # ### end Alembic commands ###
