"""lawyer_id can be nullable in lawyer_requests

Revision ID: bdd4f3c73892
Revises: 506ac4444628
Create Date: 2025-05-18 16:37:41.865639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd4f3c73892'
down_revision: Union[str, None] = '506ac4444628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyer_requests', 'lawyer_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyer_requests', 'lawyer_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
