"""changed tables tariff and subscribtion

Revision ID: bfe794227515
Revises: 6e0bc9e5e22e
Create Date: 2025-05-08 16:04:16.597445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfe794227515'
down_revision: Union[str, None] = '6e0bc9e5e22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('is_base', sa.Boolean(), nullable=False))
    op.alter_column('subscribes', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('tariffs', sa.Column('is_base', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'is_base')
    op.alter_column('subscribes', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('subscribes', 'is_base')
    # ### end Alembic commands ###
