"""changed type field

Revision ID: c8f4214cb03b
Revises: e43bd9efeae7
Create Date: 2025-05-04 14:06:29.441259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8f4214cb03b'
down_revision: Union[str, None] = 'e43bd9efeae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('name_ru', sa.String(length=255), nullable=False))
    op.alter_column('fields', 'type',
               existing_type=postgresql.ENUM('TYPE', name='fieldtypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tariffs', 'features',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('templates', 'download_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.create_foreign_key(None, 'templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.alter_column('templates', 'download_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('tariffs', 'features',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('fields', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TYPE', name='fieldtypeenum'),
               existing_nullable=False)
    op.drop_column('fields', 'name_ru')
    # ### end Alembic commands ###
