"""changes with cascade

Revision ID: e43bd9efeae7
Revises: fc10d7a17af2
Create Date: 2025-05-01 18:15:37.459895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43bd9efeae7'
down_revision: Union[str, None] = 'fc10d7a17af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_user_id_fkey', 'templates', type_='foreignkey')
    op.create_foreign_key(None, 'templates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.create_foreign_key('templates_user_id_fkey', 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
