"""changes in templates and fields

Revision ID: fc10d7a17af2
Revises: 
Create Date: 2025-05-01 17:45:17.774441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc10d7a17af2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'document_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('fields', 'template_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint('refresh_sessions_user_id_fkey', 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('tariffs', sa.Column('features', postgresql.ARRAY(sa.VARCHAR()), nullable=False))
    op.add_column('templates', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('templates', sa.Column('download_url', sa.String(), nullable=False))
    op.create_foreign_key(None, 'templates', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_column('templates', 'download_url')
    op.drop_column('templates', 'user_id')
    op.drop_column('tariffs', 'features')
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key('refresh_sessions_user_id_fkey', 'refresh_sessions', 'users', ['user_id'], ['id'])
    op.alter_column('fields', 'template_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('fields', 'document_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
